apiVersion: batch/v1
kind: Job
metadata:
  name: hermes-producer
  namespace: kafka
spec:
  template:
    metadata:
      labels:
        app: hermes-producer
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hermes-producer
          image: registry.digitalocean.com/geo/hermes-producer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: "kafka-broker-0.broker.kafka.svc.cluster.local:29092"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
