apiVersion: batch/v1
kind: CronJob
metadata:
  name: scoring-service
spec:
  schedule: "0 3 * * *"  # Run at 3am every day
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            # TODO: Determine the image build process
            - name: scoring-service
              image: scoring-service:latest
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "1024Mi"
                  cpu: "1000m"
                limits:
                  memory: "2048Mi"
                  cpu: "2000m"

