# ArgoCD Installation Manifest
# This file contains the namespace and installation for ArgoCD
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# ArgoCD will be installed using the official manifest
# Run: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
